#!/bin/sh

module="haga"
device="haga"
mode="664"

group="wheel"

/sbin/insmod ./${module}_drvr.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

rm -f /dev/${device}

mknod /dev/${device} c $major 0

chgrp $group /dev/${device}
chmod $mode /dev/${device}
