#ifndef _TSP_H_
#define _TSP_H_

/******************************************************************************
 * @name TSP API
 *****************************************************************************/

/**
 * Generate the cost table from a file in the working directory
 *
 * This must be called before doing anything else.
 *
 * The file must be a matrix with a fixed size in this form
 * n_row\t	ncol\n
 *
 * x11\t	x12\t	x13\n
 * x21\t	x22\t	x23\n
 * x31\t	x32\t	x33\n
 *
 * @param filename	The name of the file wher it is the cost table
 **/
void tsp_cost_read(char *filename);

/**
 * Destroy the table generated by tsp_cost_read()
 **/
void tsp_cost_destroy();

long long tsp_evaluate_int(unsigned int *phen, unsigned int size);

#endif /* _TSP_H_ */
